const fs = require('node:fs');
const path = require('node:path');
const out = path.join(__dirname, 'dist');
fs.mkdirSync(out, { recursive: true });
const copy = fs.readFileSync(path.join(__dirname, 'copy-revised.txt'), 'utf8').trim().split(/\r?\n\r?\n/);
const header = page => `<a class="skip" href="#main">Skip to content</a><header><a class="brand" href="index.html" aria-label="Jim Kultgen home">jim kultgen<span>.</span></a><nav aria-label="Main navigation">${[['index','Home'],['about','About'],['articles','Articles']].map(([id,label])=>`<a href="${id}.html" ${page===id?'aria-current="page"':''}>${label}</a>`).join('')}<a class="nav-connect" href="https://www.linkedin.com/in/jpkultgen/">Say hello ↗</a></nav></header>`;
const footer = `<footer><div><a class="brand" href="index.html">jim kultgen<span>.</span></a><p>Analytics, with an eye on what’s next.</p></div><div class="footer-right"><div class="footer-links"><a href="https://www.linkedin.com/in/jpkultgen/">LinkedIn ↗</a><a href="https://github.com/kultgenj">GitHub ↗</a><a href="privacy.html">Privacy</a></div><small>© ${new Date().getFullYear()} Jim Kultgen · Personal views.</small></div></footer>`;
const label = text => `<p class="eyebrow"><span></span>${text}</p>`;
const portrait = `<div class="portrait-frame"><div class="portrait-top"><span>THE PERSON BEHIND THE SITE</span><span aria-hidden="true">↗</span></div><img src="jim-portrait.jpg" alt="Jim Kultgen" width="350" height="370"><div class="portrait-bottom"><span>Jim Kultgen</span><span>Chicago, IL</span></div><svg class="portrait-sparkline" viewBox="0 0 140 80" aria-hidden="true"><path class="sparkline-baseline" d="M8 69H132"/><path class="sparkline-path" d="M8 62 L20 54 L31 61 L43 45 L54 53 L64 48 L75 56 C90 57 100 48 108 34 C115 22 120 10 124 6"/><circle cx="124" cy="6" r="3"/></svg></div>`;
const articles = JSON.parse(fs.readFileSync(path.join(__dirname, 'articles.json'), 'utf8'));
const escape = value => value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const dateFormat = new Intl.DateTimeFormat('en-US', {timeZone:'America/Chicago',month:'short',day:'numeric',year:'numeric'});
const articleCards = articles.sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)).map(article => {
 const date = new Date(article.publishedAt);
 if (Number.isNaN(date.getTime())) throw new Error('Invalid publication date: '+article.title);
 const dateLabel = dateFormat.format(date);
 const local = article.type === 'local';
 let href;
 if (local) {
  if(!/^articles\/[a-z0-9-]+\.html$/.test(article.url)) throw new Error('Local articles must use articles/slug.html');
  const file = path.join(__dirname,article.url);
  if(!fs.existsSync(file)) throw new Error('Missing local article: '+article.url);
  fs.mkdirSync(path.join(out,'articles'),{recursive:true});
  fs.copyFileSync(file,path.join(out,article.url));
  href=article.url;
 } else {
  const url = new URL(article.url);
  if(url.protocol !== 'https:' || url.hostname !== 'www.linkedin.com') throw new Error('Invalid article URL');
  href=url.href;
 }
 return '<article class="article-card"><div class="article-meta"><span>'+(local?'ON THIS SITE':'ON LINKEDIN')+'</span><time datetime="'+escape(article.publishedAt)+'" title="Publication date in US Central time">'+escape(dateLabel)+'</time></div><h2><a href="'+escape(href)+'">'+escape(article.title)+'</a></h2>'+(article.description?'<p>'+escape(article.description)+'</p>':'')+'<a class="text-link" href="'+escape(href)+'">'+(local?'Read article':'Read on LinkedIn')+' <span aria-hidden="true">↗</span></a>'+'</article>';
}).join('');
const pages = {
 index: {title:'Jim Kultgen | Analytics & AI',content:`<section class="hero"><div>${label('JIM KULTGEN / ANALYTICS & AI')}<h1>An analytics career,<br><span>evolving with AI.</span></h1><p class="intro">${copy[1]}</p><p class="intro-secondary">${copy[2]}</p><div class="actions"><a class="button" href="about.html">A little about me <span>↗</span></a><a class="text-link" href="articles.html">Articles <span>→</span></a></div></div>${portrait}</section><div class="experience-strip"><span>EXPERIENCE ACROSS</span><span>Amplitude</span><span>CARS.com</span><span>NBC Sports (TeeOff)</span><span>Kohler</span><span>Cardinal Path</span></div><section class="approach section"><div>${label('HOW I APPROACH THE WORK')}<h2>Start with<br>the question.</h2><p>My work starts with three questions. They help establish what matters, how to measure it, and what to do with what we learn.</p><a class="text-link" href="about.html">More about my background <span>↗</span></a></div><div class="questions"><p><span>01</span>What are we trying<br>to accomplish?</p><p><span>02</span>How will we know<br>if we’re successful?</p><p><span>03</span>What should we<br>do next?</p></div></section><section class="writing-preview section"><div>${label('ARTICLES')}<h2>A place to think<br>things through.</h2><p>I write about analytics and what I’m learning as AI becomes part of the work.</p><a class="text-link" href="articles.html">Visit the articles page <span>→</span></a></div><div class="notebook" aria-hidden="true"><span class="notebook-tag">WRITING ON ANALYTICS & AI</span><div class="notebook-lines"><span>What’s worth measuring?</span><i></i><i></i><i></i></div><span class="notebook-mark">jk.</span></div></section><section class="contact-band"><div>${label('LET’S TALK')}<h2>Have a question or an idea?</h2><p>You can find me on LinkedIn.</p></div><a class="button" href="https://www.linkedin.com/in/jpkultgen/">Say hello <span>↗</span></a></section>`},
 about:{title:'About | Jim Kultgen',content:`<section class="page-heading">${label('ABOUT')}<h1>I’m Jim.<br><span>I work in analytics.</span></h1><p class="lead">${copy[3]}</p></section><section class="about-layout"><div class="prose"><p>${copy[4]}</p><p>${copy[5]}</p><a class="text-link" href="https://www.linkedin.com/in/jpkultgen/">My full background on LinkedIn <span>↗</span></a></div>${portrait}</section><section class="photo-story" aria-label="Speaking and conversations"><div class="photo-story-heading">${label('IN CONVERSATION')}<h2>Sharing ideas.<br>Hearing other perspectives.</h2></div><figure class="photo-wide"><img src="jim-speaking.jpg" width="3840" height="2560" loading="lazy" alt="Jim speaking into a microphone and gesturing during a conference discussion"></figure><div class="photo-pair"><figure><img src="jim-discussion.jpg" width="3840" height="2560" loading="lazy" alt="Jim discussing an idea while seated with a microphone"></figure><figure><img src="jim-listening.jpg" width="3840" height="2560" loading="lazy" alt="Jim listening to another participant during a discussion"></figure></div></section><section id="analytics-experience" class="section experience-section" hidden>${label('ANALYTICS EXPERIENCE')}<div class="experience-row"><span>SEP 2024 — PRESENT</span><h3>Amplitude</h3><p>I lead AI strategy after joining as a Product Strategist &amp; Evangelist, bringing my analytics background to how we analyze, build, and work with AI.</p></div><div class="experience-row"><span>MAR 2020 — APR 2024</span><h3>CARS.com</h3><p>I automated marketing reporting, introduced server-side experimentation, and rolled out Amplitude so teams could answer their own questions.</p></div><div class="experience-row"><span>JAN 2019 — MAR 2020</span><h3>NBC Sports (TeeOff)</h3><p>I automated marketing reporting, repaired data collection issues, and trained teams across the business to use analytics.</p></div><div class="experience-row"><span>JUL 2016 — JAN 2019</span><h3>Kohler</h3><p>I built measurement foundations and led analytics across more than 150 digital properties, standardizing reporting and helping teams use the data.</p></div><div class="experience-row"><span>OCT 2015 — JUN 2016</span><h3>Cardinal Path</h3><p>I helped clients define KPIs, understand online customer behavior, and identify opportunities for A/B testing.</p></div></section>`},
 articles:{title:'Articles | Jim Kultgen',content:`<section class="page-heading">${label('ARTICLES')}<h1>Working things out.<br><span>Writing them down.</span></h1><p class="lead">Ideas on digital analytics and lessons from working with AI.</p></section><section class="article-grid" aria-label="Articles">${articleCards}</section><div class="article-topics"><span>ON MY MIND</span><p>Digital analytics</p><p>Measurement</p><p>AI in practice</p></div>`},
 privacy:{title:'Privacy | Jim Kultgen',content:`<section class="page-heading">${label('PRIVACY')}<h1>About your visit.</h1></section><section class="prose privacy-copy"><p>This site uses Amplitude for analytics. Visits on jimkultgen.com and www.jimkultgen.com use the production project; local previews and other domains use a separate testing project.</p><h2>Analytics and session replay</h2><p>Amplitude collects page visits, link interactions, and browser and device information. It uses identifiers to connect activity across visits. Session Replay can capture interactions such as clicks, scrolling, and visible page content. Web experiments may show different versions of a page when configured.</p><h2>Guides and surveys</h2><p>Amplitude may show guides and surveys when configured. If you respond, Amplitude processes your answers and records the survey interactions.</p><h2>Your preference</h2><p>You can turn off Amplitude for this site in this browser. This preference is stored locally and takes effect after the page reloads. It does not delete data already collected.</p><button class="button" id="analytics-toggle">Turn off analytics</button><p id="privacy-status" role="status"></p><h2>Other services</h2><p>This website uses your device’s fonts. Links to LinkedIn and GitHub take you to those services, which have their own privacy practices.</p><p>Questions? <a class="text-link" href="https://www.linkedin.com/in/jpkultgen/">Contact me on LinkedIn ↗</a></p></section>`}
};
for(const [name,page] of Object.entries(pages)) {
 const html = `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Jim Kultgen on digital analytics, measurement, and learning to work with AI."><meta name="theme-color" content="#245de8"><title>${page.title}</title><link rel="icon" href="favicon-head-transparent.png" type="image/png" sizes="64x64"><link rel="stylesheet" href="site.css"><script defer src="site-config.js"></script><script defer src="site.js"></script></head><body data-page="${name}">${header(name)}<main id="main">${page.content}</main>${footer}</body></html>\n`;
 const cleanHtml = html.replace(/(href|src)="(?!https?:|#|\/)([^"]+)"/g, (_, attr, url) => {
  const routes = {"index.html":"/", "about.html":"/about/", "articles.html":"/articles/", "privacy.html":"/privacy/"};
  return `${attr}="${routes[url] || "/" + url}"`;
 });
 const directory = name === "index" ? out : path.join(out, name);
 fs.mkdirSync(directory, {recursive:true});
 fs.writeFileSync(path.join(directory,"index.html"),cleanHtml);
 if(name !== "index") fs.writeFileSync(path.join(out,`${name}.html`),`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${page.title}</title><link rel="canonical" href="https://jimkultgen.com/${name}/"><meta http-equiv="refresh" content="0;url=/${name}/"><script>location.replace("/${name}/"+location.search+location.hash)</script></head><body><a href="/${name}/">Continue to ${name}</a></body></html>`);
}
for(const file of ['site.css','site.js','site-config.js','favicon-head-transparent.png','jim-portrait.jpg','jim-speaking.jpg','jim-discussion.jpg','jim-listening.jpg','CNAME']) fs.copyFileSync(path.join(__dirname,file),path.join(out,file));
fs.writeFileSync(path.join(out,'.nojekyll'),'');
console.log('Built Home, About, Articles, and Privacy in dist/.');
